#ifndef TOKEN_TYPE_H
#define TOKEN_TYPE_H

enum token_type
{
  /* Single-character tokens.*/
  LT_LEFT_PAREN,
  LT_RIGHT_PAREN,
  LT_LEFT_BRACE,
  LT_RIGHT_BRACE,
  LT_COMMA,
  LT_DOT,
  LT_MINUS,
  LT_PLUS,
  LT_SEMICOLON,
  LT_SLASH,
  LT_STAR,

  /* One or two character tokens.*/
  LT_BANG,
  LT_BANG_EQUAL,
  LT_EQUAL,
  LT_EQUAL_EQUAL,
  LT_GREATER,
  LT_GREATER_EQUAL,
  LT_LESS,
  LT_LESS_EQUAL,

  /* Literals.*/
  LT_IDENTIFIER,
  LT_STRING,
  LT_NUMBER,

  /* Keywords.*/
  /* This part is checked and generated by tool/hashgen */
  /* Get the hash value from hash.h:lox_fnv*/
  LT_AND = 254395046,
  LT_CLASS = -1421997057,
  LT_ELSE = -1111532560,
  LT_FALSE = 184981848,
  LT_FOR = -1393327216,
  LT_FUN = -1462011810,
  LT_IF = 959999494,
  LT_NIL = 228849900,
  LT_OR = 1563699588,
  LT_PRINT = 372738696,
  LT_RETURN = -2047985729,
  LT_SUPER = -142736940,
  LT_THIS = -634662271,
  LT_TRUE = 1303515621,
  LT_VAR = -1977227330,
  LT_WHILE = 231090382,

  LT_EOF
};

#endif /* TOKEN_TYPE_H */
