#ifndef TOKEN_TYPE_H
#define TOKEN_TYPE_H

enum token_type
{
  /* Single-character tokens.*/
  LT_LEFT_PAREN,
  LT_RIGHT_PAREN,
  LT_LEFT_BRACE,
  LT_RIGHT_BRACE,
  LT_COMMA,
  LT_DOT,
  LT_MINUS,
  LT_PLUS,
  LT_SEMICOLON,
  LT_SLASH,
  LT_STAR,

  /* One or two character tokens.*/
  LT_BANG,
  LT_BANG_EQUAL,
  LT_EQUAL,
  LT_EQUAL_EQUAL,
  LT_GREATER,
  LT_GREATER_EQUAL,
  LT_LESS,
  LT_LESS_EQUAL,

  /* Literals.*/
  LT_IDENTIFIER,
  LT_STRING,
  LT_NUMBER,

  /* Keywords.*/
  /* This part is checked and generated by tool/hashgen */
  /* Get the hash value from hash.h:lox_fnv*/
  LT_AND = 0xf29c2a6,
  LT_CLASS = 0xab3e0bff,
  LT_ELSE = 0xbdbf5bf0,
  LT_FALSE = 0xb069958,
  LT_FOR = 0xacf38390,
  LT_FUN = 0xa8db785e,
  LT_IF = 0x39386e06,
  LT_NIL = 0xda3f8ec,
  LT_OR = 0x5d342984,
  LT_PRINT = 0x16378a88,
  LT_RETURN = 0x85ee37bf,
  LT_SUPER = 0xf77e01d4,
  LT_THIS = 0xda2bd281,
  LT_TRUE = 0x4db211e5,
  LT_VAR = 0x8a25e7be,
  LT_WHILE = 0xdc628ce,

  LT_EOF
};

#endif /* TOKEN_TYPE_H */
